server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: BookManagement
          uri: http://localhost:8082
          predicates:
            - Path=/books/**, /bookLists/**, /bookDetails/**
        - id: loanmanagement
          uri: http://localhost:8083
          predicates:
            - Path=/loans/**, /loanHistories/**, /loanDetails/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: BookManagement
          uri: http://bookManagement:8080
          predicates:
            - Path=/books/**, 
        - id: loanmanagement
          uri: http://loanmanagement:8080
          predicates:
            - Path=/loans/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
