name: test
run-name: testing 
on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Prepare Test Environment
      run: |
        cd BookManagement
        mkdir -p ignore_test_file
        mv src/test/java/libraryservice/*.java ignore_test_file/
        mv ignore_test_file/LoanStatusUpdatePolicyTest.java src/test/java/libraryservice/
    - name: Compile and Run Specific Test
      run: |
        cd BookManagement
        mvn clean install -DskipTests
        mvn test -Dtest=libraryservice.LoanStatusUpdatePolicyTest -Dsurefire.useFile=false
    - name: Restore Test Files
      if: always()
      run: |
        cd BookManagement
        if [ -d "ignore_test_file" ] && [ "$(ls -A ignore_test_file)" ]; then
          mv ignore_test_file/*.java src/test/java/libraryservice/
        fi
        rm -rf ignore_test_file
    - name: Print Test Results
      if: always()
      run: |
        cd BookManagement
        cat target/surefire-reports/*.txt || true